apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity
  namespace: teamcity
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

