apiVersion: v1
kind: Pod
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: minio
  containers:
    - name: minio
      image: quay.io/minio/minio
      ports:
        - containerPort: 9000
          name: "ui"
        - containerPort: 9001
          name: "console"
      volumeMounts:
        - mountPath: "/data"
          name: storage
          subPath: minio
      env:
        - name: MINIO_ROOT_USER
          value: 'minio'
        - name: MINIO_ROOT_PASSWORD
          value: 'minio123'
      args:
        - "server"
        - "/data"
        - "--console-address"
        - ":9001"
