apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: minio
spec:
  storageClassName: minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

