apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: minio
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc
      containers:
      - image: quay.io/minio/minio
        name: minio
        ports:
          - containerPort: 9000
            name: "console"
          - containerPort: 9001
            name: "ui"
        volumeMounts:
          - mountPath: "/data"
            name: storage
        envFrom:
          - secretRef:
              name: minio-secret
        args:
          - "server"
          - "/data"
          - "--console-address"
          - ":9001"
        resources: {}
status: {}
