apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: minio
  name: minio
  namespace: minio
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: api
  - port: 9001
    protocol: TCP
    targetPort: 9001
    name: webui
  selector:
    app: minio
status:
  loadBalancer: {}
